services:
  database:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - config/database.env
    volumes:
      - data:/var/lib/postgresql/data/
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/var/app
      - logs:/var/log
volumes:
  logs: {}
  data: {}

